### ISSUE TITLE
highwayDistanceFilter Question

### ISSUE THREAD

**Issue by ghost** [dsdavids/TTLocationHandler#4]
I have a question for line 143:
if (highwayMode != _highwayMode) {
        CGFloat highwayDistanceFilter = 400.00f;

As I have changed your code to draw lines between stored location and draw passed path instead adding annotations it happend that on the corner line connects two locations and it seams that user drives a car over the building :).
I changed 'highwayDistanceFilter' to:
CGFloat highwayDistanceFilter = 20.00f;
Does this mean that new location will be stored after each 20 meters passed?
I believe that this could be solution for this issue am I right or wrong?
If you have time I can upload new code on git so you can see it.
I don't know what will happen if driver drive car too fast also.

**Comment by dsdavids** [comment]
You are correct about the distance filter, in theory. In reality, I am not sure that it is quite that simple. I am not sure you have quite that level of precision when determining the frequency that the manager sends the location. It's more like "about" 20m or some time after 20m has been travelled. Additionally, in iOS6 they want you to use activity type instead which is even more vague.

While more frequent updates will get you closer to your goal and may correct your corner cutting issue, it seems the brute force method with high inefficiency. More appropriate solution would likely involve listening for heading changes and restricting your annotations to the likely path as related to the map. You'll assume your next point is along the roadway until you have a reason to believe otherwise. When you receive a heading change you will decide where the logical point of the corner is, using an intersection if one is nearby.

This is not a functionality that I have had a need for, but if you make a fork with your changes I would be curious to experiment with it and see where I might help. 

Dean

**Comment by ghost** [comment]
I never fork on github and I changed a project a little bit so I send you code example to your email.

**Comment by ghost** [comment]
I added GPS signal strength detection and errors happens only when signal is lower.
